# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::770088366909:role/eksctl-k8singressProgram-nodegroup-NodeInstanceRole-L7ckiGkAG4Ks
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap

# define the namespace, above kind  and replace rolearn, username 
metadata:
  creationTimestamp: "2024-03-29T07:16:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1395"
  uid: 6e3df9b3-e624-4e2b-9831-4a55b32d374b
