apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "ingresses", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
