apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "ingresses", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]



# user name is already created in side the IAM in the AWS and added to the AWS-AUTH UserMap-block with "arn-id" ---> refer aws-auth.yml file userMap  .
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
- kind: User
  name: eks_user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
